#!/bin/sh
PREREQ=""
prereqs() {
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

# iw

. /usr/share/initramfs-tools/hook-functions #provides copy_exec

for f in $(ls /usr/sbin/iw*); do copy_exec $f $f; done
for f in $(ls /usr/bin/iw*); do copy_exec $f $f; done
copy_exec /usr/libexec/iwd /bin/iwd

